# Defaults tasks for role geoip2
- name: Importing specific distro variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - vars
    - always


- name: Installing python GeoIP2 pkg
  ansible.builtin.yum:
    name: "{{ geoip_pkgs }}"
    state: latest

- name: Adding script to update GeoLite2-{City,Country} DBs 
  ansible.builtin.template:
    src: geoip_update.j2
    dest: /usr/libexec/centos/geoip_update
    mode: 0750
  register: geoip_download_script  

- name: Downloading GeoIP DB on init
  ansible.builtin.command: 
    cmd: /usr/libexec/centos/geoip_update
  when: geoip_download_script is changed
 
- name: Scheduling GeoLite DB update
  ansible.builtin.cron:
    name: GeoLite DB update
    minute: '5'
    hour: '9'
    day: '2'
    user: root
    job: /usr/libexec/centos/geoip_update
